output "frontend_application_url" {
  value       = "https://${azurerm_linux_web_app.frontend_app.default_hostname}"
  description = "The frontend application URL."
}

output "backend_application_url" {
  value       = "https://${azurerm_linux_web_app.backend_app.default_hostname}"
  description = "The backend application URL."
}

output "frontend_application_fqdn" {
  value       = azurerm_linux_web_app.frontend_app.default_hostname
  description = "The frontend application fully qualified domain name (FQDN)."
}

output "backend_application_fqdn" {
  value       = azurerm_linux_web_app.backend_app.default_hostname
  description = "The backend application fully qualified domain name (FQDN)."
}

output "frontend_application_caf_name" {
  value       = azurecaf_name.linux_app_service_frontend.result
  description = "The frontend application."
}

output "backend_application_caf_name" {
  value       = azurecaf_name.linux_app_service_backend.result
  description = "The backend application."
}

output "container_registry_name" {
  value       = azurecaf_name.container_registry.result
  description = "The Docker Container Registry name generated by the Azure Cloud Adoption Framework."
}
