output "frontend_url" {
  value       = module.application.frontend_application_url
  description = "The frontend application URL."
}

output "backend_url" {
  value       = module.application.backend_application_url
  description = "The backend application URL."
}


output "resource_group" {
  value       = azurerm_resource_group.main.name
  description = "The resource group."
}

output "frontend_application_name" {
  value       = module.application.frontend_application_caf_name
  description = "The frontend application name generated by the Azure Cloud Adoption Framework."
}

output "backend_application_name" {
  value       = module.application.backend_application_caf_name
  description = "The backend application name generated by the Azure Cloud Adoption Framework."
}

output "container_registry_name" {
  value       = module.application.container_registry_name
  description = "The Docker Container Registry name generated by the Azure Cloud Adoption Framework."
}
